### ISSUE TITLE
Reconnect after network error

### ISSUE THREAD

**Issue by teodor-pripoae** [tony612/grpc-elixir#3]
Hi,

I'm testing the following scenario against a golang server:

- run rpc request => everything ok
- stop server
- run rpc request => error
- start server again
- run rpc request => it should reconnect and return correct answer

```
iex(9)> {:ok, channel} = GRPC.Stub.connect("localhost:8080", insecure: true)
{:ok,
 %GRPC.Channel{adapter: GRPC.Adapter.Chatterbox.Client, host: "localhost",
  payload: %{pid: #PID<0.450.0>}, port: 8080, scheme: "http"}}
iex(10)> request = Uav.LookupSlugRequest.new(slug: "grpc-elixir")
%Uav.LookupSlugRequest{slug: "grpc-elixir"}
iex(11)> response = Uav.RPC.Stub.lookup_slug(channel, request)
22:46:13.607 [info] [client] Stream 1 WindowUpdate 5
%Uav.LookupSlugResponse{ref_id: nil}
```

I stopped the golang server.

```
iex(12)> response = Uav.RPC.Stub.lookup_slug(channel, request)
** (exit) exited in: :gen_fsm.sync_send_all_state_event(#PID<0.450.0>, {:new_stream, #PID<0.425.0>})
    ** (EXIT) no process
    (stdlib) gen_fsm.erl:249: :gen_fsm.sync_send_all_state_event/2
      (grpc) lib/grpc/adapter/chatterbox/client.ex:37: GRPC.Adapter.Chatterbox.Client.send_header/2
      (grpc) lib/grpc/adapter/chatterbox/client.ex:28: GRPC.Adapter.Chatterbox.Client.send_request/3
      (grpc) lib/grpc/adapter/chatterbox/client.ex:21: GRPC.Adapter.Chatterbox.Client.unary/3
      (grpc) lib/grpc/stub.ex:70: GRPC.Stub.send_request/5
```

I started the golang server again.

```
iex(13)> response = Uav.RPC.Stub.lookup_slug(channel, request)
** (exit) exited in: :gen_fsm.sync_send_all_state_event(#PID<0.450.0>, {:new_stream, #PID<0.425.0>})
    ** (EXIT) no process
    (stdlib) gen_fsm.erl:249: :gen_fsm.sync_send_all_state_event/2
      (grpc) lib/grpc/adapter/chatterbox/client.ex:37: GRPC.Adapter.Chatterbox.Client.send_header/2
      (grpc) lib/grpc/adapter/chatterbox/client.ex:28: GRPC.Adapter.Chatterbox.Client.send_request/3
      (grpc) lib/grpc/adapter/chatterbox/client.ex:21: GRPC.Adapter.Chatterbox.Client.unary/3
      (grpc) lib/grpc/stub.ex:70: GRPC.Stub.send_request/5
```

The channel should try to reconnect on next RPC call, at least this is what golang and ruby clients are doing. Any advices ?

Thank you,
Teodor

**Comment by tony612** [comment]
You're right, I did't implement reconnection yet. I'll look into this after finishing my own busy work recently. Before that, maybe you can try to reconnect in your own code?

**Comment by tony612** [comment]
It's fixed on master. Please update grpc. Please let me know if you have further problems. Thanks!
