### ISSUE TITLE
Process not alive after switch to hex package

### ISSUE THREAD

**Issue by ospaarmann** [tony612/grpc-elixir#52]
I switched to the hex package (0.3.0-alpha.1). My app is now throwing this error when I try to connect to the server (Dgraph) via the `GRPC.Stub`.

```
01:26:40.282 [error] GenServer #PID<0.6941.0> terminating
** (stop) exited in: :gen_server.call(:gun_sup, {:start_child, [#PID<0.6941.0>, 'localhost', 9080, %{protocols: [:http2], transport: :tcp}]}, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib) gen_server.erl:214: :gen_server.call/3
    /Users/ole/exdgraph/deps/gun/src/gun.erl:137: :gun.open/3
    lib/grpc/adapter/gun.ex:32: GRPC.Adapter.Gun.connect_insecurely/2
    (ex_dgraph) lib/exdgraph/protocol.ex:23: ExDgraph.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
```

Adding grpc to the list of applications in my mix.exs fixed this but the docs state that this is only necessary for Elixir before 1.4 (I'm using 1.6).

**Comment by tony612** [comment]
Could you show what's the application section of your `mix.exs`, like:
```
  def application do
    [extra_applications: [:logger]]
  end
```

**Comment by ospaarmann** [comment]
Now it looks like this and the problem is gone: 

```
  def application do
    [
      applications: [
        :logger,
        :poolboy,
        :db_connection,
        :retry,
        :grpc
      ]
    ]
  end
```

I thought that it is not necessary to add `:grpc` to the list of applications when using Elixir 1.6.

**Comment by tony612** [comment]
You need to delete `: applications` and use `extra_applications`, otherwise you have to add all applications.
