### ISSUE TITLE
Getting Malformed response: missing :status in HEADERS frame

### ISSUE THREAD

**Issue by sezaru** [tony612/grpc-elixir#55]
Hello,

I'm trying to use grpc-elixir client to connect to a LND GRPC server, the commands I do are:
```
ca_path = Path.expand("./tls/tls.cert", :code.priv_dir(:elixir_lnd))
credential = GRPC.Credential.new(ssl: [cacertfile: ca_path])

{:ok, channel} = GRPC.Stub.connect("localhost:10009", [cred: credential])
{:ok, reply} = channel |> Lnrpc.Lightning.Stub.get_info(Lnrpc.GetInfoRequest.new())
```

As far as the server getting the message, it seems to work great, but I do get an error from its response:
```
iex(5)> {:ok, reply} = channel |> Lnrpc.Lightning.Stub.get_info(Lnrpc.GetInfoRequest.new())
{:ok, reply} = channel |> Lnrpc.Lightning.Stub.get_info(Lnrpc.GetInfoRequest.new())
** (CaseClauseError) no case clause matching: {:error, %GRPC.RPCError{message: "{:stream_error, :protocol_error, :\"Malformed response; missing :status in HEADERS frame. (RFC7540 8.1.2.4)\"}", status: 2}}
    (grpc) lib/grpc/stub.ex:320: GRPC.Stub.recv_body/5
    (grpc) lib/grpc/stub.ex:290: GRPC.Stub.recv/2
```

My Protobuf file is like this:
```
syntax = "proto3";

package lnrpc;
service Lightning {
    rpc GetInfo (GetInfoRequest) returns (GetInfoResponse) { }
}

message GetInfoRequest {
}
message GetInfoResponse {

    /// The identity pubkey of the current node.
    string identity_pubkey = 1 [json_name = "identity_pubkey"];

    /// If applicable, the alias of the current node, e.g. "bob"
    string alias = 2 [json_name = "alias"];

    /// Number of pending channels
    uint32 num_pending_channels = 3 [json_name = "num_pending_channels"];

    /// Number of active channels
    uint32 num_active_channels = 4 [json_name = "num_active_channels"];

    /// Number of peers
    uint32 num_peers = 5 [json_name = "num_peers"];

    /// The node's current view of the height of the best block
    uint32 block_height = 6 [json_name = "block_height"];

    /// The node's current view of the hash of the best block
    string block_hash = 8 [json_name = "block_hash"];

    /// Whether the wallet's view is synced to the main chain
    bool synced_to_chain = 9 [json_name = "synced_to_chain"];

    /// Whether the current node is connected to testnet
    bool testnet = 10 [json_name = "testnet"];

    /// A list of active chains the node is connected to
    repeated string chains = 11 [json_name = "chains"];

    /// The URIs of the current node.
    repeated string uris = 12 [json_name = "uris"];

    /// Timestamp of the block best known to the wallet
    int64 best_header_timestamp = 13 [ json_name = "best_header_timestamp" ];
}
```

Which generated this file:
```
defmodule Lnrpc.GetInfoRequest do
  @moduledoc false
  use Protobuf, syntax: :proto3

  defstruct []

end

defmodule Lnrpc.GetInfoResponse do
  @moduledoc false
  use Protobuf, syntax: :proto3

  @type t :: %__MODULE__{
    identity_pubkey:       String.t,
    alias:                 String.t,
    num_pending_channels:  non_neg_integer,
    num_active_channels:   non_neg_integer,
    num_peers:             non_neg_integer,
    block_height:          non_neg_integer,
    block_hash:            String.t,
    synced_to_chain:       boolean,
    testnet:               boolean,
    chains:                [String.t],
    uris:                  [String.t],
    best_header_timestamp: integer
  }
  defstruct [:identity_pubkey, :alias, :num_pending_channels, :num_active_channels, :num_peers, :block_height, :block_hash, :synced_to_chain, :testnet, :chains, :uris, :best_header_timestamp]

  field :identity_pubkey, 1, type: :string
  field :alias, 2, type: :string
  field :num_pending_channels, 3, type: :uint32
  field :num_active_channels, 4, type: :uint32
  field :num_peers, 5, type: :uint32
  field :block_height, 6, type: :uint32
  field :block_hash, 8, type: :string
  field :synced_to_chain, 9, type: :bool
  field :testnet, 10, type: :bool
  field :chains, 11, repeated: true, type: :string
  field :uris, 12, repeated: true, type: :string
  field :best_header_timestamp, 13, type: :int64
end

defmodule Lnrpc.Lightning.Service do
  @moduledoc false
  use GRPC.Service, name: "lnrpc.Lightning"
  rpc :GetInfo, Lnrpc.GetInfoRequest, Lnrpc.GetInfoResponse
end

defmodule Lnrpc.Lightning.Stub do
  @moduledoc false
  use GRPC.Stub, service: Lnrpc.Lightning.Service
end
```

I'm using latest master (I did try the branches too but same problem) code

**Comment by sezaru** [comment]
Looking at issue #53 I tried changing gun version to 1.0.0.0-pre.5 with:
```{:gun, "1.0.0-pre.5", override: true},```
That did the trick, now I receive the response correctly.

Are you planning changing the default version of gun to that one in the near future?

**Comment by tony612** [comment]
I've contacted with the owner to retire 1.0.0-pre.4b version https://hex.pm/packages/gun.
I will lock the version in the next release.
