### ISSUE TITLE
0.3.0-alpha.2 blocks GRPC servers from receiving messages

### ISSUE THREAD

**Issue by JayH5** [tony612/grpc-elixir#59]
We have a GRPC streaming server that works something like this using the GRPC 0.3.0-alpha.1:
```elixir
@spec stream_listeners(Enumerable.t(), Stream.t()) :: Stream.t()
def stream_listeners(req_enum, stream0) do
  :ok = Publisher.subscribe(Publisher, :listeners, self())
  handle_requests(req_enum, stream0)
end

@spec handle_requests(Enumerable.t(), Stream.t()) :: Stream.t()
defp handle_requests(req_enum, stream0) do
  req_enum |> Enum.reduce(stream0, &handle_request(&1, &2))
end

@spec handle_request(DiscoveryRequest.t(), Stream.t()) :: Stream.t()
defp handle_request(_request, stream) do
  receive do
    {:listeners, version_info, resources} ->
      send_reply(stream, version_info, resources)
  end
end

@spec send_reply(Stream.t(), String.t(), [unquote(resource_type).t]) :: Stream.t()
defp send_reply(stream, version_info, resources),
  do: GRPC.Server.send_reply(stream, mkresponse(version_info, resources))
```

I've tried to adapt the server for 0.3.0-alpha.2, but the `receive` call seems to be blocked by grpc-elixir. Messages are never received and an error is produced like:
```
12:41:16.486 [error] ** (CaseClauseError) no case clause matching: {:listeners, "1", ...
    (grpc) lib/grpc/adapter/cowboy.ex:86: GRPC.Adapter.Cowboy.read_stream/2
    (elixir) lib/stream.ex:1466: Stream.do_unfold/4
    (elixir) lib/enum.ex:1919: Enum.each/2
    (grpc) lib/grpc/server.ex:134: GRPC.Server.do_handle_request/5
    (grpc) lib/grpc/adapter/cowboy/handler.ex:180: GRPC.Adapter.Cowboy.Handler.do_call_rpc/3
    (grpc) lib/grpc/adapter/cowboy/handler.ex:168: GRPC.Adapter.Cowboy.Handler.call_rpc/3
```

I think the relevant change is tony612/grpc@d1abe70a6cad6dac4a3f8235d883d7c896989560 and the message we send our server is actually received in the [adapter handler's `sync_call` function](https://github.com/tony612/grpc-elixir/blob/dcdb5ebacf3957c989782ab63acfb615771fcfc6/lib/grpc/adapter/cowboy/handler.ex#L75-L77), which then doesn't match any clause in the [adapter's `read_stream` function](https://github.com/tony612/grpc-elixir/blob/dcdb5ebacf3957c989782ab63acfb615771fcfc6/lib/grpc/adapter/cowboy.ex#L86-L107).

We would like to be able to send messages to our server as it makes streaming easier. Can we find a way to filter the messages that the adapter handler receives or change the system in some way to allow messages to be sent to the server?

Thanks for the great library!

**Comment by JayH5** [comment]
@tony612 yes, that does seem to fix things. Thanks!
